import { Html, OrbitControls, Stars } from '@react-three/drei'
import { Canvas, useFrame } from '@react-three/fiber'
import { useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { mockConjunctionPairs, mockOrbitalObjects } from '../data/mockOrbitalData'
const colors = { normal: '#6ee7f5', elevated: '#f3b85d', critical: '#ff7469' }
const at = (o, a) => new THREE.Vector3(Math.cos(a) * o.radius, 0, Math.sin(a) * o.radius).applyAxisAngle(new THREE.Vector3(1, 0, 0), o.inclination)
function Earth() { return <group><mesh><sphereGeometry args={[1.72, 64, 64]} /><meshStandardMaterial color="#0b2637" roughness={.78} metalness={.38} emissive="#041421" emissiveIntensity={.9} /></mesh><mesh scale={1.026}><sphereGeometry args={[1.72, 64, 64]} /><meshBasicMaterial color="#50ddec" transparent opacity={.09} side={THREE.BackSide} /></mesh><mesh rotation={[.2, .5, 0]}><sphereGeometry args={[1.725, 64, 64]} /><meshBasicMaterial color="#1a6177" wireframe transparent opacity={.13} /></mesh><pointLight color="#52e4f5" intensity={5} distance={7} /></group> }
function Path({ object, active }) { const points = useMemo(() => Array.from({ length: 129 }, (_, i) => at(object, i / 128 * Math.PI * 2)), [object]); return <line><bufferGeometry><bufferAttribute attach="attributes-position" count={points.length} array={new Float32Array(points.flatMap(p => p.toArray()))} itemSize={3} /></bufferGeometry><lineBasicMaterial color={active ? colors[object.risk] : '#2c9bb1'} transparent opacity={active ? .94 : .35} /></line> }
function Marker({ object, active, onSelect }) { const ref = useRef(); const [hover, setHover] = useState(false); useFrame(({ clock }) => ref.current?.position.copy(at(object, object.phase + clock.getElapsedTime() * object.speed))); return <group ref={ref}><mesh onClick={e => { e.stopPropagation(); onSelect(object.id) }} onPointerOver={() => setHover(true)} onPointerOut={() => setHover(false)}><sphereGeometry args={[active ? .14 : .09, 16, 16]} /><meshBasicMaterial color={colors[object.risk]} /><pointLight color={colors[object.risk]} intensity={active ? 2.4 : 1.2} distance={1.7} /></mesh>{(active || hover) && <Html distanceFactor={11} center style={{ pointerEvents: 'none' }}><span className="orbital-label">{object.name}</span></Html>}</group> }
function Link({ objects }) { const ref = useRef(); useFrame(({ clock }) => { const t = clock.getElapsedTime(); ref.current.geometry.setFromPoints(objects.map(o => at(o, o.phase + t * o.speed))) }); return <line ref={ref}><bufferGeometry /><lineBasicMaterial color="#ff7469" transparent opacity={.9} /></line> }
function Scene({ selectedThreat, onObjectSelect }) { const ids = [selectedThreat.objectA, selectedThreat.objectB]; const pair = mockConjunctionPairs.find(p => p.every(id => ids.includes(id)))?.map(id => mockOrbitalObjects.find(o => o.id === id)); return <><color attach="background" args={['#06101a']} /><fog attach="fog" args={['#06101a', 12, 24]} /><ambientLight intensity={.5} /><Stars radius={30} depth={12} count={900} factor={1.5} saturation={0} fade speed={.2} /><Earth />{mockOrbitalObjects.map(o => <Path key={`p-${o.id}`} object={o} active={ids.includes(o.id)} />)}{pair && <Link objects={pair} />}{mockOrbitalObjects.map(o => <Marker key={o.id} object={o} active={ids.includes(o.id)} onSelect={onObjectSelect} />)}<OrbitControls makeDefault enableRotate enableZoom enableDamping dampingFactor={.08} enablePan={false} minDistance={6.5} maxDistance={13} minPolarAngle={.55} maxPolarAngle={2.45} autoRotate autoRotateSpeed={.15} /></> }
export default function OrbitalScene(props) { return <Canvas className="orbital-canvas-root" camera={{ position: [7.4, 5.5, 8.5], fov: 41 }} dpr={[1, 1.7]}><Scene {...props} /></Canvas> }
