"""JSON-friendly data models returned by the orbit propagator."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Any


@dataclass(frozen=True)
class Position:
    """Position in kilometres in the TEME coordinate frame."""

    x_km: float
    y_km: float
    z_km: float


@dataclass(frozen=True)
class Velocity:
    """Velocity in kilometres per second in the TEME coordinate frame."""

    x_km_s: float
    y_km_s: float
    z_km_s: float


@dataclass(frozen=True)
class PropagationResult:
    """A satellite state vector generated by SGP4.

    SGP4 produces coordinates in the True Equator Mean Equinox (TEME) frame.
    ``to_dict`` returns only JSON-serializable values for downstream consumers.
    """

    object_id: str
    object_name: str
    timestamp: datetime
    position: Position
    velocity: Velocity
    coordinate_frame: str = "TEME"

    def to_dict(self) -> dict[str, Any]:
        """Return this result in the public, JSON-serializable format."""
        data = asdict(self)
        data["timestamp"] = self.timestamp.astimezone(timezone.utc).isoformat().replace(
            "+00:00", "Z"
        )
        return data
